### ISSUE TITLE
Several icons became too small or disappeared

### ISSUE THREAD

**Issue by chicoary** [sebastianconcept/PharoDawnTheme#2]
![Dawn Theme icons disapearing issue](https://user-images.githubusercontent.com/7659991/77835404-eef7be00-712a-11ea-9c05-ae2823432cd4.png)

**Comment by sebastianconcept** [comment]
@chicoary sorry ddelay, just checked here after a long while.

Yes it needs some love to work in Pharo9 and 10.

I'm taking a look at the moment.

**Comment by sebastianconcept** [comment]
<img width="1387" alt="Screen Shot 2023-02-01 at 18 22 23" src="https://user-images.githubusercontent.com/475508/216166221-3de9980d-56bb-4eb8-a8dd-7495e618b411.png">
It's looking good in Pharo 9 now.

Do you confirm @chicoary

**Comment by chicoary** [comment]
Yes.

**Comment by sebastianconcept** [comment]
@chicoary can you confirm how it goes in Pharo 11?

```st
Metacello new 
	baseline: 'PharoDawnTheme';
	repository: 'github://sebastianconcept/PharoDawnTheme:latest';
	load.
```

**Comment by sebastianconcept** [comment]
@chicoary I'm closing it for now but feel free to comment to reopen if you see the issue repeating.

Thanks for reporting
