### ISSUE TITLE
Spotter is not adopted for theme

### ISSUE THREAD

**Issue by Bajger** [sebastianconcept/PharoDawnTheme#3]
Hi Sebastian!
When i tried to open Spotter (shift+enter) in P9 (latest-devel) with new PharoDawnTheme it was shown as this: 
![image](https://user-images.githubusercontent.com/45875448/78352273-62c11d00-75a8-11ea-8071-f1a90a3271db.png)

Is there easy way to adopt also Spotter tool for new theme?

**Comment by sebastianconcept** [comment]
Thanks for the heads up @Bajger last time I used it was in P7 but I'm missing it.

I'm trying to make it work again in P9 and hopefully P10 too.

**Comment by sebastianconcept** [comment]
<img width="1111" alt="Screen Shot 2023-02-01 at 18 25 49" src="https://user-images.githubusercontent.com/475508/216166813-73f44aa9-6ef7-4ec3-a431-8dec26f81549.png">

@Bajger does it looks good there now? 

I've loaded it in a fresh Pharo9 with:

```smalltalk
Metacello new 
	baseline: 'PharoDawnTheme';
	repository: 'github://sebastianconcept/PharoDawnTheme';
	load.
```

**Comment by Bajger** [comment]
@sebastianconcept Hi Sebastian! I like your theme, din't use it since then, since it blocked me in searching. But happy to use it again. Thank you ❤️

**Comment by Bajger** [comment]
@sebastianconcept I've just tested on fresh P10 (stable) 64bit: 
![image](https://user-images.githubusercontent.com/45875448/216292384-7b298b6e-029d-4d4f-b167-27782f185028.png)

**Comment by sebastianconcept** [comment]
Hi @Bajger I was able to reproduce that issue with `curl https://get.pharo.org/ | bash` which downloads stable VM but latest image.

If you download it with:

```
VERSION=100
  curl get.pharo.org/64/$VERSION | bash
  curl get.pharo.org/64/vm$VERSION | bash
```
Works?

**Comment by Bajger** [comment]
@sebastianconcept: Hi! Still same result for Spotter (tested on MacOS): 
![image](https://user-images.githubusercontent.com/45875448/223151220-73aa0a73-d6e8-4991-b079-80eb94843871.png)

**Comment by sebastianconcept** [comment]
Closing for now.
@Bajger if you happen to use Pharo and want to try this theme again, let me know how it goes in Pharo 11 with :
```smalltalk
Metacello new 
	baseline: 'PharoDawnTheme';
	repository: 'github://sebastianconcept/PharoDawnTheme:latest';
	load.
```

**Comment by Bajger** [comment]
It works! Thanks! Maybe it could be one of the core themes. I like this color scheme.
