### ISSUE TITLE
`SubclassResponsibility: PharoDawnTheme class had the subclass responsibility to implement #colorConfiguratorClass` encountered while attempting to load with Metacello in Pharo 11

### ISSUE THREAD

**Issue by capsulecorplab** [sebastianconcept/PharoDawnTheme#9]
![Screenshot from 2024-01-11 02-31-08](https://github.com/sebastianconcept/PharoDawnTheme/assets/14095576/81e1935c-2db3-40d1-a38e-2020b9f96147)

**Comment by sebastianconcept** [comment]
I will open PR in a bit

cc/ @capsulecorplab 
 
![p11Dawn](https://github.com/sebastianconcept/PharoDawnTheme/assets/475508/1bbfe679-06bc-45df-8723-e9cd92c72a28)

**Comment by sebastianconcept** [comment]
Merged fix here https://github.com/sebastianconcept/PharoDawnTheme/pull/10
Closing
